name = "gig"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.39.0"
pprint = ">= 1.0.3 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
startest = ">= 0.2.4 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.0.0"

glance = ">= 3.0.0 and < 4.0.0"
# glance = { path = "../glance" }

[dev-dependencies]
