
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"



String gleam_io_do_get_line(Int length);
Nil gleam_io_do_print_error(String s);
Nil gleam_io_do_print(String s);