
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

typedef struct Tuple3_String_String_List_String Tuple3_String_String_List_String;
typedef Pointer List_String;

Bool eq_Tuple3_String_String_List_String(Tuple3_String_String_List_String a, Tuple3_String_String_List_String b);
String inspect_Tuple3_String_String_List_String(Tuple3_String_String_List_String a);
Tuple3_String_String_List_String new_Tuple3_String_String_List_String(String f0, String f1, List_String f2);
Bool eq_List_String(List_String a, List_String b);
String inspect_List_String(List_String a);
extern const Pointer new_Empty_String;
List_String new_Cons_String(String f0, List_String f1);

Tuple3_String_String_List_String argv_do();

struct Tuple3_String_String_List_String{
String f0;
String f1;
List_String f2;
};

struct Empty_String{
};
struct Cons_String{
String f0;
List_String f1;
};