
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

Nil panic_exit(String a0);
Int length_bit_array(BitArray a0);
BitArray slice_bit_array(BitArray a0, Int a1, Int a2);
Int index_bit_array_int(BitArray a0, Int a1, Int a2);
String index_bit_array_string(BitArray a0, Int a1, Int a2);
Nil write_bit_array(BitArray a0, BitArray a1, Int a2, Int a3);
Nil write_bit_array_int(Int a0, BitArray a1, Int a2, Int a3);
Nil write_bit_array_string(String a0, BitArray a1, Int a2, Int a3);
String drop_start_string(String a0, Int a1);
Bool starts_with_string(String a0, String a1);
String append_string(String a0, String a1);
Int length_string(String a0);
Float div_Float(Float a0, Float a1);
Float mul_Float(Float a0, Float a1);
Float sub_Float(Float a0, Float a1);
Float add_Float(Float a0, Float a1);
Bool gte_Float(Float a0, Float a1);
Bool lte_Float(Float a0, Float a1);
Bool gt_Float(Float a0, Float a1);
Bool lt_Float(Float a0, Float a1);
Int negate_Int(Int a0);
Int rem_Int(Int a0, Int a1);
Int div_Int(Int a0, Int a1);
Int mul_Int(Int a0, Int a1);
Int sub_Int(Int a0, Int a1);
Int add_Int(Int a0, Int a1);
Bool gte_Int(Int a0, Int a1);
Bool lte_Int(Int a0, Int a1);
Bool gt_Int(Int a0, Int a1);
Bool lt_Int(Int a0, Int a1);
Bool negate_bool(Bool a0);
Bool or_bool(Bool a0, Bool a1);
Bool and_bool(Bool a0, Bool a1);