
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

Nil panic_exit(String message);
Int length_bit_array(BitArray a);
BitArray slice_bit_array(BitArray a, Int offset, Int length);
Int index_bit_array_int(BitArray a, Int offset, Int length);
String index_bit_array_string(BitArray a, Int offset, Int length);
Nil write_bit_array(BitArray value, BitArray to, Int to_offset, Int len);
Nil write_bit_array_int(Int value, BitArray to, Int at_offset, Int len);
Nil write_bit_array_string(String value, BitArray to, Int at_offset, Int len);
String drop_start_string(String string, Int count);
Bool starts_with_string(String string, String prefix);
String append_string(String a, String b);
Int length_string(String a);
Float div_Float(Float a, Float b);
Float mul_Float(Float a, Float b);
Float sub_Float(Float a, Float b);
Float add_Float(Float a, Float b);
Bool gte_Float(Float a, Float b);
Bool lte_Float(Float a, Float b);
Bool gt_Float(Float a, Float b);
Bool lt_Float(Float a, Float b);
Int negate_Int(Int a);
Int rem_Int(Int a, Int b);
Int div_Int(Int a, Int b);
Int mul_Int(Int a, Int b);
Int sub_Int(Int a, Int b);
Int add_Int(Int a, Int b);
Bool gte_Int(Int a, Int b);
Bool lte_Int(Int a, Int b);
Bool gt_Int(Int a, Int b);
Bool lt_Int(Int a, Int b);
Bool negate_bool(Bool b);
Bool or_bool(Bool a, Bool b);
Bool and_bool(Bool a, Bool b);