
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

typedef struct simplifile_FileInfo simplifile_FileInfo;
typedef Pointer List_String;
typedef Pointer simplifile_FileError;
typedef Pointer Result_BitArray_simplifile_FileError;
typedef Pointer Result_Bool_simplifile_FileError;
typedef Pointer Result_List_String_simplifile_FileError;
typedef Pointer Result_Nil_simplifile_FileError;
typedef Pointer Result_simplifile_FileInfo_simplifile_FileError;

Bool eq_simplifile_FileInfo(simplifile_FileInfo a, simplifile_FileInfo b);
String inspect_simplifile_FileInfo(simplifile_FileInfo a);
simplifile_FileInfo new_simplifile_FileInfo(Int f0, Int f1, Int f2, Int f3, Int f4, Int f5, Int f6, Int f7, Int f8, Int f9);
Bool eq_List_String(List_String a, List_String b);
String inspect_List_String(List_String a);
extern const Pointer new_Empty_String;
List_String new_Cons_String(String f0, List_String f1);
Bool eq_simplifile_FileError(simplifile_FileError a, simplifile_FileError b);
String inspect_simplifile_FileError(simplifile_FileError a);
extern const Pointer new_simplifile_Eacces;
extern const Pointer new_simplifile_Eagain;
extern const Pointer new_simplifile_Ebadf;
extern const Pointer new_simplifile_Ebadmsg;
extern const Pointer new_simplifile_Ebusy;
extern const Pointer new_simplifile_Edeadlk;
extern const Pointer new_simplifile_Edeadlock;
extern const Pointer new_simplifile_Edquot;
extern const Pointer new_simplifile_Eexist;
extern const Pointer new_simplifile_Efault;
extern const Pointer new_simplifile_Efbig;
extern const Pointer new_simplifile_Eftype;
extern const Pointer new_simplifile_Eintr;
extern const Pointer new_simplifile_Einval;
extern const Pointer new_simplifile_Eio;
extern const Pointer new_simplifile_Eisdir;
extern const Pointer new_simplifile_Eloop;
extern const Pointer new_simplifile_Emfile;
extern const Pointer new_simplifile_Emlink;
extern const Pointer new_simplifile_Emultihop;
extern const Pointer new_simplifile_Enametoolong;
extern const Pointer new_simplifile_Enfile;
extern const Pointer new_simplifile_Enobufs;
extern const Pointer new_simplifile_Enodev;
extern const Pointer new_simplifile_Enolck;
extern const Pointer new_simplifile_Enolink;
extern const Pointer new_simplifile_Enoent;
extern const Pointer new_simplifile_Enomem;
extern const Pointer new_simplifile_Enospc;
extern const Pointer new_simplifile_Enosr;
extern const Pointer new_simplifile_Enostr;
extern const Pointer new_simplifile_Enosys;
extern const Pointer new_simplifile_Enotblk;
extern const Pointer new_simplifile_Enotdir;
extern const Pointer new_simplifile_Enotsup;
extern const Pointer new_simplifile_Enxio;
extern const Pointer new_simplifile_Eopnotsupp;
extern const Pointer new_simplifile_Eoverflow;
extern const Pointer new_simplifile_Eperm;
extern const Pointer new_simplifile_Epipe;
extern const Pointer new_simplifile_Erange;
extern const Pointer new_simplifile_Erofs;
extern const Pointer new_simplifile_Espipe;
extern const Pointer new_simplifile_Esrch;
extern const Pointer new_simplifile_Estale;
extern const Pointer new_simplifile_Etxtbsy;
extern const Pointer new_simplifile_Exdev;
extern const Pointer new_simplifile_NotUtf8;
simplifile_FileError new_simplifile_Unknown(String f0);
Bool eq_Result_BitArray_simplifile_FileError(Result_BitArray_simplifile_FileError a, Result_BitArray_simplifile_FileError b);
String inspect_Result_BitArray_simplifile_FileError(Result_BitArray_simplifile_FileError a);
Result_BitArray_simplifile_FileError new_Ok_BitArray_simplifile_FileError(BitArray f0);
Result_BitArray_simplifile_FileError new_Error_BitArray_simplifile_FileError(simplifile_FileError f0);
Bool eq_Result_Bool_simplifile_FileError(Result_Bool_simplifile_FileError a, Result_Bool_simplifile_FileError b);
String inspect_Result_Bool_simplifile_FileError(Result_Bool_simplifile_FileError a);
Result_Bool_simplifile_FileError new_Ok_Bool_simplifile_FileError(Bool f0);
Result_Bool_simplifile_FileError new_Error_Bool_simplifile_FileError(simplifile_FileError f0);
Bool eq_Result_List_String_simplifile_FileError(Result_List_String_simplifile_FileError a, Result_List_String_simplifile_FileError b);
String inspect_Result_List_String_simplifile_FileError(Result_List_String_simplifile_FileError a);
Result_List_String_simplifile_FileError new_Ok_List_String_simplifile_FileError(List_String f0);
Result_List_String_simplifile_FileError new_Error_List_String_simplifile_FileError(simplifile_FileError f0);
Bool eq_Result_Nil_simplifile_FileError(Result_Nil_simplifile_FileError a, Result_Nil_simplifile_FileError b);
String inspect_Result_Nil_simplifile_FileError(Result_Nil_simplifile_FileError a);
Result_Nil_simplifile_FileError new_Ok_Nil_simplifile_FileError(Nil f0);
Result_Nil_simplifile_FileError new_Error_Nil_simplifile_FileError(simplifile_FileError f0);
Bool eq_Result_simplifile_FileInfo_simplifile_FileError(Result_simplifile_FileInfo_simplifile_FileError a, Result_simplifile_FileInfo_simplifile_FileError b);
String inspect_Result_simplifile_FileInfo_simplifile_FileError(Result_simplifile_FileInfo_simplifile_FileError a);
Result_simplifile_FileInfo_simplifile_FileError new_Ok_simplifile_FileInfo_simplifile_FileError(simplifile_FileInfo f0);
Result_simplifile_FileInfo_simplifile_FileError new_Error_simplifile_FileInfo_simplifile_FileError(simplifile_FileError f0);

Result_simplifile_FileInfo_simplifile_FileError simplifile_file_info(String a0);
Result_Bool_simplifile_FileError simplifile_is_directory(String a0);
Result_Bool_simplifile_FileError simplifile_is_file(String a0);
Result_BitArray_simplifile_FileError simplifile_read_bits(String a0);
Result_List_String_simplifile_FileError simplifile_read_directory(String a0);
Result_Nil_simplifile_FileError simplifile_write_bits(String a0, BitArray a1);

struct simplifile_FileInfo{
Int f0;
Int f1;
Int f2;
Int f3;
Int f4;
Int f5;
Int f6;
Int f7;
Int f8;
Int f9;
};

struct Empty_String{
};
struct Cons_String{
String f0;
List_String f1;
};

struct simplifile_Eacces{
};
struct simplifile_Eagain{
};
struct simplifile_Ebadf{
};
struct simplifile_Ebadmsg{
};
struct simplifile_Ebusy{
};
struct simplifile_Edeadlk{
};
struct simplifile_Edeadlock{
};
struct simplifile_Edquot{
};
struct simplifile_Eexist{
};
struct simplifile_Efault{
};
struct simplifile_Efbig{
};
struct simplifile_Eftype{
};
struct simplifile_Eintr{
};
struct simplifile_Einval{
};
struct simplifile_Eio{
};
struct simplifile_Eisdir{
};
struct simplifile_Eloop{
};
struct simplifile_Emfile{
};
struct simplifile_Emlink{
};
struct simplifile_Emultihop{
};
struct simplifile_Enametoolong{
};
struct simplifile_Enfile{
};
struct simplifile_Enobufs{
};
struct simplifile_Enodev{
};
struct simplifile_Enolck{
};
struct simplifile_Enolink{
};
struct simplifile_Enoent{
};
struct simplifile_Enomem{
};
struct simplifile_Enospc{
};
struct simplifile_Enosr{
};
struct simplifile_Enostr{
};
struct simplifile_Enosys{
};
struct simplifile_Enotblk{
};
struct simplifile_Enotdir{
};
struct simplifile_Enotsup{
};
struct simplifile_Enxio{
};
struct simplifile_Eopnotsupp{
};
struct simplifile_Eoverflow{
};
struct simplifile_Eperm{
};
struct simplifile_Epipe{
};
struct simplifile_Erange{
};
struct simplifile_Erofs{
};
struct simplifile_Espipe{
};
struct simplifile_Esrch{
};
struct simplifile_Estale{
};
struct simplifile_Etxtbsy{
};
struct simplifile_Exdev{
};
struct simplifile_NotUtf8{
};
struct simplifile_Unknown{
String f0;
};

struct Ok_BitArray_simplifile_FileError{
BitArray f0;
};
struct Error_BitArray_simplifile_FileError{
simplifile_FileError f0;
};

struct Ok_Bool_simplifile_FileError{
Bool f0;
};
struct Error_Bool_simplifile_FileError{
simplifile_FileError f0;
};

struct Ok_List_String_simplifile_FileError{
List_String f0;
};
struct Error_List_String_simplifile_FileError{
simplifile_FileError f0;
};

struct Ok_Nil_simplifile_FileError{
Nil f0;
};
struct Error_Nil_simplifile_FileError{
simplifile_FileError f0;
};

struct Ok_simplifile_FileInfo_simplifile_FileError{
simplifile_FileInfo f0;
};
struct Error_simplifile_FileInfo_simplifile_FileError{
simplifile_FileError f0;
};