
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

typedef struct { enum {Ok_Int_Nil_TAG, Error_Int_Nil_TAG} tag; union {struct Ok_Int_Nil *v0; struct Error_Int_Nil *v1;} ptr; } Result_Int_Nil;

Bool eq_Result_Int_Nil(Result_Int_Nil a, Result_Int_Nil b);
Bool lt_Result_Int_Nil(Result_Int_Nil a, Result_Int_Nil b);
String inspect_Result_Int_Nil(Result_Int_Nil a);
Result_Int_Nil new_Ok_Int_Nil(Int value);
Result_Int_Nil new_Error_Int_Nil(Nil value);

Int gleam_int_bitwise_and(Int a0, Int a1);
Result_Int_Nil gleam_int_do_base_parse(String a0, Int a1);
Result_Int_Nil gleam_int_parse(String a0);
String gleam_int_to_string(Int a0);

struct Ok_Int_Nil{
Int value;
};
struct Error_Int_Nil{
Nil value;
};