
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

String gleam_io_do_get_line(Int a0);
Nil gleam_io_do_print(String a0);
Nil gleam_io_do_print_error(String a0);
