
// This file is automatically generated.
// Please do not edit it.

#include "builtin.h"

typedef struct Tuple2_String_String Tuple2_String_String;
typedef struct { enum {Ok_Tuple2_String_String_Nil_TAG, Error_Tuple2_String_String_Nil_TAG} tag; union {struct Ok_Tuple2_String_String_Nil *v0; struct Error_Tuple2_String_String_Nil *v1;} ptr; } Result_Tuple2_String_String_Nil;

Bool eq_Tuple2_String_String(Tuple2_String_String a, Tuple2_String_String b);
Bool lt_Tuple2_String_String(Tuple2_String_String a, Tuple2_String_String b);
String inspect_Tuple2_String_String(Tuple2_String_String a);
Tuple2_String_String new_Tuple2_String_String(String el0, String el1);
Bool eq_Result_Tuple2_String_String_Nil(Result_Tuple2_String_String_Nil a, Result_Tuple2_String_String_Nil b);
Bool lt_Result_Tuple2_String_String_Nil(Result_Tuple2_String_String_Nil a, Result_Tuple2_String_String_Nil b);
String inspect_Result_Tuple2_String_String_Nil(Result_Tuple2_String_String_Nil a);
Result_Tuple2_String_String_Nil new_Ok_Tuple2_String_String_Nil(Tuple2_String_String value);
Result_Tuple2_String_String_Nil new_Error_Tuple2_String_String_Nil(Nil value);

String append_string(String a0, String a1);
Int compare_string(String a0, String a1);
String slice_string(String a0, Int a1, Int a2);
Bool ends_with_string(String a0, String a1);
Result_Tuple2_String_String_Nil pop_grapheme_string(String a0);
Bool starts_with_string(String a0, String a1);

struct Tuple2_String_String{
String el0;
String el1;
};

struct Ok_Tuple2_String_String_Nil{
Tuple2_String_String value;
};
struct Error_Tuple2_String_String_Nil{
Nil value;
};