name: Gig CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Erlang/OTP and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.11.1"
          rebar3-version: "3"

      - name: Install libgc Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgc-dev

      - name: Check Code Formatting
        run: gleam format --check src test

      - name: Download Project Dependencies
        run: gleam deps download

      - name: Run Project Tests
        run: gleam test
